name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
         
      - name: Install Go module dependencies
        run: cd ./backend && go get
        
      - name: Build backend
        run: cd ./backend && go build

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install frontend dependencies
        run: npm ci --prefix ./frontend

      - name: Build frontend
        run: CI=false npm run build --prefix ./frontend

      # Add more steps here for testing, linting, etc.

  qodana:
    name: Qodana
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2023.1.0
